/**
 * Catalog of CS demo question banks.
 * Files live in src/data/bankPacks/ (generated by scripts/generateCsBanks.mjs).
 */

export type DemoBankMeta = {
  num: number;
  slug: string;
  title: string;
  file: string;
};

/**
 * Original five seed banks — stable bank ids (`seed_qb_dsa_*`, etc.) for existing quizzes.
 * Content is now full-size packs like the rest of the catalog.
 */
export type CoreDemoBankMeta = DemoBankMeta & {
  idKey: "dsa" | "algo" | "prog" | "systems" | "nlp";
};

export const CORE_DEMO_BANK_CATALOG: CoreDemoBankMeta[] = [
  {
    num: 1,
    idKey: "dsa",
    slug: "data-structures",
    title: "Data Structures",
    file: "01-data-structures.json",
  },
  {
    num: 2,
    idKey: "algo",
    slug: "algorithms-complexity",
    title: "Algorithms & Complexity",
    file: "02-algorithms-complexity.json",
  },
  {
    num: 3,
    idKey: "prog",
    slug: "programming-fundamentals",
    title: "Programming Fundamentals",
    file: "03-programming-fundamentals.json",
  },
  {
    num: 4,
    idKey: "systems",
    slug: "systems-os-networking",
    title: "Systems, OS & Networking",
    file: "04-systems-os-networking.json",
  },
  {
    num: 5,
    idKey: "nlp",
    slug: "nlp-language-models",
    title: "NLP & Language Models",
    file: "05-nlp-language-models.json",
  },
];

export type NewDemoBankMeta = DemoBankMeta;

/** Banks 6–46. */
export const NEW_DEMO_BANK_CATALOG: NewDemoBankMeta[] = [
  { num: 6, slug: "python", title: "Python Programming", file: "06-python.json" },
  { num: 7, slug: "java", title: "Java Programming", file: "07-java.json" },
  { num: 8, slug: "c", title: "C Programming", file: "08-c.json" },
  { num: 9, slug: "cpp", title: "C++ Programming", file: "09-cpp.json" },
  { num: 10, slug: "discrete-math", title: "Discrete Mathematics", file: "10-discrete-math.json" },
  {
    num: 11,
    slug: "probability-stats",
    title: "Probability and Statistics for CS",
    file: "11-probability-stats.json",
  },
  {
    num: 12,
    slug: "linear-algebra",
    title: "Linear Algebra for CS",
    file: "12-linear-algebra.json",
  },
  {
    num: 13,
    slug: "computer-organization",
    title: "Computer Organization and Digital Logic",
    file: "13-computer-organization.json",
  },
  { num: 14, slug: "operating-systems", title: "Operating Systems", file: "14-operating-systems.json" },
  {
    num: 15,
    slug: "computer-networks",
    title: "Computer Networks and Network Theory",
    file: "15-computer-networks.json",
  },
  { num: 16, slug: "cybersecurity", title: "Cybersecurity", file: "16-cybersecurity.json" },
  { num: 17, slug: "cryptography", title: "Cryptography", file: "17-cryptography.json" },
  { num: 18, slug: "databases", title: "Databases", file: "18-databases.json" },
  {
    num: 19,
    slug: "parallel-distributed",
    title: "Parallel and Distributed Systems",
    file: "19-parallel-distributed.json",
  },
  {
    num: 20,
    slug: "compilers",
    title: "Compilers and Programming Languages",
    file: "20-compilers.json",
  },
  {
    num: 21,
    slug: "embedded-iot",
    title: "Embedded Systems and IoT",
    file: "21-embedded-iot.json",
  },
  { num: 22, slug: "html-css", title: "HTML and CSS", file: "22-html-css.json" },
  {
    num: 23,
    slug: "web-technologies",
    title: "Web Technologies",
    file: "23-web-technologies.json",
  },
  {
    num: 24,
    slug: "javascript-typescript",
    title: "JavaScript and TypeScript",
    file: "24-javascript-typescript.json",
  },
  {
    num: 25,
    slug: "software-engineering",
    title: "Software Engineering",
    file: "25-software-engineering.json",
  },
  {
    num: 26,
    slug: "devops-sre",
    title: "DevOps and Site Reliability",
    file: "26-devops-sre.json",
  },
  {
    num: 27,
    slug: "mobile-cloud",
    title: "Mobile and Cloud Computing",
    file: "27-mobile-cloud.json",
  },
  {
    num: 28,
    slug: "functional-programming",
    title: "Functional Programming",
    file: "28-functional-programming.json",
  },
  {
    num: 29,
    slug: "concurrent-programming",
    title: "Concurrent Programming",
    file: "29-concurrent-programming.json",
  },
  {
    num: 30,
    slug: "theory-of-computation",
    title: "Theory of Computation",
    file: "30-theory-of-computation.json",
  },
  {
    num: 31,
    slug: "formal-methods",
    title: "Formal Methods and Verification",
    file: "31-formal-methods.json",
  },
  {
    num: 32,
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    file: "32-artificial-intelligence.json",
  },
  { num: 33, slug: "machine-learning", title: "Machine Learning", file: "33-machine-learning.json" },
  { num: 34, slug: "data-science", title: "Data Science", file: "34-data-science.json" },
  {
    num: 35,
    slug: "computer-vision",
    title: "Computer Vision",
    file: "35-computer-vision.json",
  },
  {
    num: 36,
    slug: "information-retrieval",
    title: "Information Retrieval and Search",
    file: "36-information-retrieval.json",
  },
  {
    num: 37,
    slug: "computer-graphics",
    title: "Computer Graphics",
    file: "37-computer-graphics.json",
  },
  {
    num: 38,
    slug: "human-computer-interaction",
    title: "Human–Computer Interaction",
    file: "38-human-computer-interaction.json",
  },
  {
    num: 39,
    slug: "computer-ethics",
    title: "Computer Ethics and Professional Practice",
    file: "39-computer-ethics.json",
  },
  {
    num: 40,
    slug: "numerical-methods",
    title: "Numerical Methods and Scientific Computing",
    file: "40-numerical-methods.json",
  },
  {
    num: 41,
    slug: "game-development",
    title: "Game Development",
    file: "41-game-development.json",
  },
  {
    num: 42,
    slug: "quantum-computing",
    title: "Quantum Computing",
    file: "42-quantum-computing.json",
  },
  {
    num: 43,
    slug: "blockchain",
    title: "Blockchain and Decentralized Systems",
    file: "43-blockchain.json",
  },
  { num: 44, slug: "robotics", title: "Robotics", file: "44-robotics.json" },
  { num: 45, slug: "bioinformatics", title: "Bioinformatics", file: "45-bioinformatics.json" },
  {
    num: 46,
    slug: "capstone-research",
    title: "Capstone Projects and Research Methods",
    file: "46-capstone-research.json",
  },
];

export function newDemoBankId(slug: string, courseId: string): string {
  return `seed_qb_${slug}_${courseId}`;
}

/** Stable ids for the original five banks (existing quizzes/bank pools keep working). */
export function demoQuestionBankIds(courseId: string) {
  return {
    dsa: `seed_qb_dsa_${courseId}`,
    algo: `seed_qb_algo_${courseId}`,
    prog: `seed_qb_prog_${courseId}`,
    systems: `seed_qb_systems_${courseId}`,
    nlp: `seed_qb_nlp_${courseId}`,
  };
}

/** Every bundled demo bank id for a course (original five + catalog 6–46). */
export function allDemoSeedBankIds(courseId: string): Set<string> {
  return new Set([
    ...Object.values(demoQuestionBankIds(courseId)),
    ...NEW_DEMO_BANK_CATALOG.map((m) => newDemoBankId(m.slug, courseId)),
  ]);
}
