/**
 * Curated concept tuples: [term, definition, distractor, distractor, distractor].
 * Consumed by scripts/generateDemoBanks.mjs to build seed question banks.
 */

export const CORE_CONCEPTS = {
  python: [
    ["List", "Ordered mutable sequence supporting indexing and slicing", "Immutable key-value map", "Unordered unique set only", "OS process handle"],
    ["Tuple", "Ordered immutable sequence often used for fixed records", "Mutable dynamic array", "Hash map with string keys", "Thread lock object"],
    ["Dictionary", "Mutable mapping of hashable keys to values", "Ordered immutable sequence", "Fixed-size buffer", "Priority queue heap"],
    ["Set", "Unordered collection of unique hashable elements", "Ordered list allowing duplicates", "Stack with LIFO only", "Binary tree node"],
    ["List comprehension", "Expression that builds a list from an iterable with optional filter", "Recursive descent rule", "Decorator that caches", "Context manager protocol"],
    ["Generator", "Iterator that yields values lazily via yield", "Eager list materializer", "Mutex critical section", "Metaclass factory"],
    ["Decorator", "Callable that wraps another function to extend behavior", "GC generation counter", "Virtualenv pin file", "Type comment only"],
    ["Context manager", "Object supporting with-statement enter/exit for resources", "Async event-loop scheduler", "Import hook finder", "Peephole optimizer"],
    ["Duck typing", "Compatibility based on behavior rather than declared type", "Strict nominal inheritance only", "Template expansion", "Manual refcounting"],
    ["GIL", "CPython lock allowing one thread to run bytecode at a time", "GPU shader lock", "Consensus quorum", "SQL isolation level"],
    ["*args", "Collects extra positional arguments into a tuple", "Keyword-only dict merger", "Instance attribute cache", "Exception chain marker"],
    ["**kwargs", "Collects extra keyword arguments into a dict", "Positional-only pack", "Metaclass prepare hook", "Awaitable wrapper"],
    ["f-string", "String literal with embedded expressions prefixed by f", "Raw bytes hex dump", "Regex compile flag", "Pickle protocol"],
    ["None", "Singleton representing absence of a value", "Boolean false alias", "Empty list singleton", "NaN float sentinel"],
    ["is vs ==", "is tests identity; == tests value equality", "Both always identical", "is compares hashes only", "== compares addresses only"],
    ["EAFP", "Style preferring try/except over preemptive checks", "LBYL-only analysis", "Mandatory null checks", "Borrow checker"],
    ["venv", "Isolated environment with its own installed packages", "System site-packages only", "Docker layer cache", "CMake build dir"],
    ["pip", "Installer for packages from PyPI and other indexes", "Java bytecode linker", "npm auditor", "apt mirror"],
    ["__init__", "Constructor called after instance allocation", "Module finalizer", "Metaclass interceptor", "Weakref callback"],
    ["__str__", "Human-readable string representation method", "Hash for dict keys", "Pickle reducer", "Async aclose"],
    ["lambda", "Anonymous expression-bodied function", "Named classmethod", "Generator send target", "TypeVar bound"],
    ["map", "Applies a function across items of iterables", "In-place sort key", "Dict merge operator", "Set update"],
    ["filter", "Yields items for which a predicate is true", "List reverse helper", "String partition", "Enum factory"],
    ["zip", "Pairs items from multiple iterables until one ends", "Dict keys view", "Heap push-pop", "Glob expander"],
    ["dataclass", "Decorator generating init/repr/eq boilerplate", "ABC metaclass", "Task group", "ctypes pack"],
    ["type hint", "Annotation describing expected types for checkers", "Runtime mandatory cast", "Bytecode cache", "Finder stub"],
    ["asyncio", "Library for concurrent code using async/await", "Threading GIL bypass", "Shared ctypes only", "Futures executor only"],
    ["pathlib", "Object-oriented filesystem path API", "os.system wrapper", "mkstemp only", "which locator"],
    ["Exception", "Base for most catchable error types", "SystemExit only", "KeyboardInterrupt base", "Warning alone"],
    ["MRO", "Method resolution order for multiple inheritance", "GC threshold", "Import cycle breaker", "Frame eval API"],
  ],
  java: [
    ["JVM", "Virtual machine executing Java bytecode portably", "AOT-only native linker", "Browser DOM runtime", "SQL planner"],
    ["JDK", "Kit with compiler, tools, and libraries for development", "JRE without javac", "Maven mirror", "JIT profile"],
    ["JRE", "Runtime needed to execute compiled Java applications", "Source debugger only", "Annotation path", "module-info gen"],
    ["bytecode", "Platform-neutral instructions produced by javac", "Native x86 opcodes", "LLVM bitcode only", "Python marshal"],
    ["class", "Blueprint defining fields and methods for objects", "Package-private interface", "Enum constant pool", "Record ctor"],
    ["interface", "Type declaring method contracts for implementors", "Concrete fields-only class", "Static nested enum", "Synced block"],
    ["abstract class", "Non-instantiable class that may declare abstract methods", "Final utility class", "Retention policy", "VarHandle fence"],
    ["inheritance", "Subclass acquiring members from a superclass", "Delegation-only composition", "Package sealing", "ServiceLoader SPI"],
    ["polymorphism", "Using objects via a common supertype", "Static overloading only", "Primitive widening", "Generic erasure"],
    ["encapsulation", "Hiding state behind controlled accessors", "Public field exposure", "package-info docs", "opens directive"],
    ["override", "Subclass method replacing a superclass method", "Overload different arity", "Synthetic bridge", "Default conflict"],
    ["overload", "Same method name with different parameter lists", "Covariant override", "Varargs packing", "MethodHandle bind"],
    ["ArrayList", "Resizable array-backed List implementation", "LinkedHashSet only", "ConcurrentSkipList", "PriorityBlockingQueue"],
    ["HashMap", "Hash-table Map allowing one null key", "TreeMap only", "IdentityHashMap", "WeakHashMap"],
    ["HashSet", "Set backed by a HashMap of unique elements", "CopyOnWriteArrayList", "ArrayDeque", "BitSet"],
    ["String", "Immutable character sequence with pool interning", "Mutable StringBuilder", "Shared char[] always", "UTF-16 buffer only"],
    ["StringBuilder", "Mutable character sequence for concatenation", "Interned String", "Unsynced StringBuffer", "NIO CharBuffer"],
    ["checked exception", "Exception that must be declared or handled", "Error subclass only", "Unchecked RuntimeException", "Suppressed list"],
    ["RuntimeException", "Unchecked exception for programming errors", "Checked IOException", "JVM Error only", "APT fault"],
    ["synchronized", "Mutual exclusion via an object's monitor", "volatile visibility only", "CAS loop", "LockSupport park"],
    ["volatile", "Ensures cross-thread visibility of field writes", "Exclusion lock", "final freeze only", "transient skip"],
    ["garbage collection", "Automatic reclaim of unreachable objects", "Manual free", "ReferenceQueue only", "Phantom only"],
    ["package", "Namespace grouping classes and access control", "Module layer only", "JAR manifest", "Classpath glob"],
    ["import", "Makes another type usable by simple name", "Static field import only", "requires module", "opens reflect"],
    ["static", "Member belonging to the class, not instances", "Instance-only field", "Default interface method", "Record component"],
    ["final", "Prevents reassignment, override, or subclassing", "volatile barrier", "JNI native", "strictfp FP"],
    ["generics", "Compile-time type parameters erased at runtime", "Reified arguments", "C++ templates", "Wildcard only"],
    ["Optional", "Container that may hold a non-null value", "Nullable annotation", "Stream terminal", "CompletableFuture"],
    ["Stream API", "Fluent pipelines for bulk sequence operations", "Iterator.remove only", "toArray only", "Spliterator"],
    ["record", "Immutable data carrier with generated members", "JavaBean mutable", "Enum with methods", "Sealed permit"],
  ],
  c: [
    ["pointer", "Variable holding the address of another object", "Java reference only", "Python descriptor", "Go itable"],
    ["array", "Contiguous sequence of same-type elements", "Linked node list", "Hash buckets", "String rope"],
    ["struct", "Aggregate grouping named members", "Overlapping union only", "Enum tags", "Bit-field flags"],
    ["union", "Type whose members share storage", "Padded struct", "Flexible array", "Anonymous struct"],
    ["malloc", "Allocates uninitialized heap bytes returning void*", "stack alloca", "calloc zeroing", "realloc shrink"],
    ["free", "Releases heap memory from malloc-family", "Stack unwind", "GC finalize", "munmap mapping"],
    ["sizeof", "Yields size in bytes of a type or expression", "alignof ABI", "offsetof distance", "typeof GNU"],
    ["null pointer", "Pointer value referring to no valid object", "Dangling freed addr", "Wild uninitialized", "Function thunk"],
    ["undefined behavior", "Action with no constraints in the C standard", "Impl-defined I/O", "Unspecified order only", "Locale printf"],
    ["header file", "Included file declaring interfaces across units", "Object file input", "Shared .so", "PCH only"],
    ["preprocessor", "Phase for includes, macros, and conditionals", "Linker resolution", "Loader relocate", "JIT codegen"],
    ["#define", "Directive creating a macro substitution", "typedef alias", "inline hint", "enum constant"],
    ["typedef", "Alias name for an existing type", "Function-like macro", "Struct tag alone", "restrict qualifier"],
    ["const", "Qualifier promising no modification via that lvalue", "volatile MMIO", "restrict alias", "static duration"],
    ["volatile", "Value may change outside program control", "const correctness", "_Atomic only", "register hint"],
    ["static function", "Function with internal linkage to one TU", "extern visibility", "inline across TUs", "noreturn attr"],
    ["extern", "Declares a symbol defined elsewhere", "static file scope", "Tentative def", "Common BSS"],
    ["stack", "Region for automatic variables and frames", "Heap arena", "Data globals", "Anonymous mmap"],
    ["heap", "Region for dynamically allocated memory", "Stack locals", "rodata literals", "TLS locals"],
    ["segmentation fault", "Fault from invalid memory access (SIGSEGV)", "Bus alignment error", "FE_INVALID float", "Illegal insn"],
    ["buffer overflow", "Writing past the end of an allocated buffer", "Use-after-free only", "Double free alone", "Integer wrap"],
    ["C string", "char array terminated by a null byte", "Length-prefixed string", "UTF-16 Java String", "Rope tree"],
    ["strcpy", "Copies a string including the terminator", "strncpy always pads", "Overlapping memcpy", "strdup wrapper"],
    ["printf", "Formatted output to stdout", "scanf input", "puts only", "write syscall"],
    ["FILE*", "Opaque stdio stream handle", "int file descriptor", "DIR* stream", "va_list args"],
    ["errno", "Thread-local code set by failing library calls", "Win32 GetLastError", "COM HRESULT", "Checked exceptions"],
    ["bitwise AND", "Operator & true where both bits are 1", "Logical && short-circuit", "XOR exclusive", "Left shift"],
    ["left shift", "Operator << moving bits to higher significance", "Arithmetic right shift", "Rotate intrinsic", "AND mask"],
    ["function pointer", "Pointer used to call a function by address", "void* data only", "C++ vtable slot", "Closure env"],
    ["restrict", "Hint that a pointer uniquely accesses an object", "const immutability", "volatile observe", "memory_order"],
  ],
  cpp: [
    ["RAII", "Binding resource lifetime to object lifetime via ctor/dtor", "Manual free everywhere", "Garbage collection only", "Go defer only"],
    ["constructor", "Special member initializing a new object", "Destructor cleanup only", "Assignment operator", "Friend declaration"],
    ["destructor", "Special member releasing resources at end of lifetime", "Copy constructor", "Move assignment", "Conversion operator"],
    ["reference", "Alias to an existing object that cannot be reseated", "Nullable raw pointer", "shared_ptr control block", "optional wrapper"],
    ["lvalue reference", "Reference bound to a named persistent object", "rvalue ref to temporary", "Forwarding ref", "Pointer arithmetic"],
    ["rvalue reference", "Reference designed to bind to temporaries for moves", "const lvalue ref only", "Raw T* pointer", "span view"],
    ["move semantics", "Transferring resources from one object to another", "Deep copy always", "Reference counting only", "Garbage collection"],
    ["std::vector", "Dynamic contiguous array container", "std::list nodes", "std::map tree", "std::unordered_set"],
    ["std::string", "Ownable contiguous character sequence", "string_view non-owning", "const char* only", "rope node"],
    ["template", "Compile-time parameterized code generation", "Java runtime generics", "Macro textual only", "virtual dispatch"],
    ["overload resolution", "Choosing the best matching function candidate", "Name mangling only", "ADL Koenig only", "SFINAE failure"],
    ["namespace", "Named scope preventing symbol collisions", "C translation unit", "Java package import", "Python module path"],
    ["class vs struct", "Default private vs public members; both are class types", "struct cannot have methods", "class cannot be POD", "union equivalence"],
    ["virtual function", "Dynamically dispatched method via vtable", "static binding only", "inline always", "constexpr only"],
    ["pure virtual", "Abstract method declared with = 0", "final override", "defaulted special member", "deleted function"],
    ["inheritance", "Derived class extending a base class", "Composition only", "Friend injection", "CRTP only"],
    ["polymorphism", "Calling derived behavior through base interfaces", "Template monomorphization only", "Macro expansion", "Function pointers only"],
    ["smart pointer", "Owning pointer type managing lifetime automatically", "Raw new without delete", "C malloc", "observer_ptr only"],
    ["unique_ptr", "Exclusive-ownership smart pointer", "shared_ptr shared ownership", "weak_ptr cache", "auto_ptr deprecated twin"],
    ["shared_ptr", "Reference-counted shared ownership pointer", "unique_ptr exclusive", "raw observing pointer", "intrusive_ptr only"],
    ["const correctness", "Using const to express non-mutation guarantees", "mutable everything", "volatile MMIO only", "constexpr freeze"],
    ["STL algorithm", "Generic operation like sort/find on iterator ranges", "Container member only", "OpenMP pragma", "SIMD intrinsic"],
    ["iterator", "Object abstracting position in a sequence", "Raw index only", "Generator coroutine only", "span size"],
    ["exception", "Control transfer via throw/catch for error handling", "errno return codes only", "setjmp/longjmp only", "optional error"],
    ["constexpr", "Expression/function usable in constant evaluation", "runtime-only inline", "volatile compute", "asm block"],
    ["lambda", "Anonymous function object with optional captures", "Function pointer only", "std::function type erasure only", "macro callable"],
    ["rule of five", "If you define one special member, consider all five", "Rule of zero only", "Copy-only types", "Aggregate init only"],
    ["undefined behavior", "Program with no defined meaning under the standard", "Unspecified order only", "Implementation-defined size", "Locale facet"],
    ["header", "Interface declarations typically included by users", "Translation unit .cpp only", "Module partition only", "PCH binary"],
    ["linkage", "How names are shared across translation units", "Calling convention only", "Name mangling alone", "ABI padding"],
  ],
  discrete: [
    ["proposition", "Declarative sentence that is true or false", "Open predicate only", "Imperative command", "Rhetorical question"],
    ["conjunction", "Logical AND of two propositions", "Exclusive OR", "Material implication", "Logical NOR"],
    ["disjunction", "Logical OR of two propositions", "NAND gate only", "Biconditional", "Exclusive conjunction"],
    ["implication", "If-then conditional proposition", "Biconditional only", "Negation flip", "XOR parity"],
    ["biconditional", "True when both sides share truth value", "One-way implication", "Exclusive or", "Nand expression"],
    ["predicate", "Statement with variables becoming proposition when bound", "Closed tautology only", "Propositional atom", "Modal operator"],
    ["quantifier", "Symbol expressing forall or exists over a domain", "Boolean connective", "Set comprehension", "Relation symbol"],
    ["set", "Collection of distinct objects called elements", "Ordered tuple", "Multiset with counts", "Fuzzy membership only"],
    ["subset", "Every element of A is also in B", "Proper superset", "Disjoint union", "Power set twin"],
    ["power set", "Set of all subsets of a given set", "Cartesian product", "Symmetric difference", "Partition blocks"],
    ["Cartesian product", "Set of ordered pairs from two sets", "Union of sets", "Intersection only", "Disjoint sum"],
    ["relation", "Subset of a Cartesian product between sets", "Function total map only", "Equivalence class alone", "Partial order cover"],
    ["function", "Relation assigning each domain element one codomain value", "Multi-valued relation", "Partial order", "Graph adjacency"],
    ["injection", "One-to-one function; distinct inputs map distinct", "Surjective onto only", "Bijection inverse", "Constant function"],
    ["surjection", "Onto function; every codomain element is hit", "Injective one-to-one", "Partial function", "Embedding"],
    ["bijection", "Both injective and surjective; invertible", "Injection only", "Surjection only", "Homomorphism"],
    ["equivalence relation", "Reflexive, symmetric, and transitive relation", "Strict order", "Partial function", "Tournament digraph"],
    ["partial order", "Reflexive, antisymmetric, transitive relation", "Total equivalence", "Symmetric closure", "Matching"],
    ["graph", "Vertices connected by edges", "Tree only", "Hypergraph edges", "Finite automaton"],
    ["degree", "Number of edges incident to a vertex", "Path length", "Chromatic number", "Girth"],
    ["tree", "Connected acyclic undirected graph", "Cyclic connected graph", "DAG with multiple roots", "Complete bipartite"],
    ["DFS", "Depth-first traversal exploring deep before wide", "BFS layer order", "Dijkstra priority", "Prim MST"],
    ["BFS", "Breadth-first traversal by distance layers", "DFS recursion stack", "Topological Kahn", "Kruskal union"],
    ["combinatorics", "Counting arrangements and selections", "Measure theory", "Linear algebra spectra", "Topology continuity"],
    ["permutation", "Ordered arrangement of distinct objects", "Combination unordered", "Partition set", "Derangement only"],
    ["combination", "Unordered selection of objects", "Permutation ordered", "Cartesian pair", "Injection count"],
    ["pigeonhole principle", "If more items than containers, some container shares", "Inclusion-exclusion", "Generating functions", "Burnside lemma"],
    ["proof by induction", "Base case plus inductive step for naturals", "Proof by contradiction only", "Direct expansion only", "Model checking"],
    ["modular arithmetic", "Arithmetic of remainders modulo n", "Real interval arithmetic", "Floating IEEE", "p-adic valuation only"],
    ["recurrence", "Sequence defined in terms of earlier terms", "Closed form only", "Generating ODE", "Markov chain only"],
  ],
  probstats: [
    ["sample space", "Set of all possible outcomes of an experiment", "Event sigma-algebra only", "Random variable range", "Prior distribution"],
    ["event", "Subset of the sample space", "Outcome atom only", "Density function", "Likelihood ratio"],
    ["probability", "Measure of likelihood assigned to events", "Raw frequency count only", "Utility payoff", "Entropy bits"],
    ["conditional probability", "Probability of A given B has occurred", "Joint probability only", "Marginal sum", "Bayes posterior alone"],
    ["independence", "Events whose joint equals product of marginals", "Mutually exclusive", "Correlation zero only", "Conditional dependence"],
    ["random variable", "Measurable function from outcomes to numbers", "Deterministic constant", "Sample mean only", "Hypothesis test"],
    ["PMF", "Probability mass function for discrete RVs", "PDF continuous density", "CDF cumulative only", "Hazard rate"],
    ["PDF", "Probability density for continuous RVs", "PMF discrete masses", "Quantile function", "Survival function"],
    ["CDF", "Probability that RV is at most a value", "PDF derivative only", "PMF table", "MGF transform"],
    ["expectation", "Probability-weighted average of an RV", "Mode peak only", "Median middle", "Variance spread"],
    ["variance", "Expected squared deviation from the mean", "Mean absolute deviation only", "Skewness asymmetry", "Kurtosis tails"],
    ["Bernoulli", "Binary trial with success probability p", "Poisson counts", "Gaussian continuous", "Uniform discrete"],
    ["Binomial", "Count of successes in n independent Bernoulli trials", "Geometric waiting", "Hypergeometric depleting", "NegBin failures"],
    ["Poisson", "Count of rare events in fixed interval/rate", "Binomial fixed n", "Exponential waiting", "Gamma shape"],
    ["Normal distribution", "Bell-shaped continuous distribution (Gaussian)", "Uniform flat", "Exponential memoryless", "Cauchy heavy tails"],
    ["CLT", "Sample means approach normality for large n", "LLN almost-sure average", "Slutsky theorem", "Delta method"],
    ["Law of Large Numbers", "Sample average converges to expectation", "CLT normality", "Borel-Cantelli", "Glivenko-Cantelli"],
    ["Bayes theorem", "Updates prior to posterior given likelihood", "Frequentist p-value", "MLE point only", "MAP without prior"],
    ["likelihood", "Probability of data viewed as function of parameters", "Prior belief", "Posterior odds", "Evidence marginal"],
    ["hypothesis test", "Procedure deciding to reject a null hypothesis", "Point estimation only", "Interval estimation only", "Descriptive plot"],
    ["p-value", "Probability of data as extreme assuming null true", "Posterior probability", "Effect size", "Power of test"],
    ["confidence interval", "Interval procedure covering parameter with stated rate", "Credible Bayesian interval", "Prediction interval only", "Tolerance interval"],
    ["correlation", "Linear association measure between variables", "Causation proof", "Mutual information only", "Rank concordance only"],
    ["covariance", "Expected product of centered variables", "Correlation scaled", "Variance of sum only", "Precision matrix"],
    ["MLE", "Parameter maximizing likelihood of observed data", "MAP with prior", "Method of moments only", "Bayesian posterior mean"],
    ["bias", "Difference between estimator expectation and truth", "Variance of estimator", "MSE combined", "Consistency limit"],
    ["sampling", "Selecting observations from a population", "Census entire population", "Bootstrap resample only", "Cross-validation fold"],
    ["A/B test", "Experiment comparing variants via statistics", "Observational study only", "Simulation Monte Carlo", "Bandit regret"],
    ["entropy", "Uncertainty measure of a distribution in bits/nats", "Variance second moment", "KL divergence alone", "Cross-entropy loss only"],
    ["standard deviation", "Square root of variance; spread scale", "IQR robust range", "MAD median abs", "Range max-min"],
  ],
  linalg: [
    ["vector", "Element of a vector space; often an ordered tuple", "Scalar field element", "Matrix only", "Tensor rank-3 only"],
    ["matrix", "Rectangular array representing a linear map", "Vector column only", "Scalar determinant", "Permutation cycle"],
    ["scalar", "Field element scaling vectors", "Vector magnitude only", "Matrix trace", "Eigenvector"],
    ["dot product", "Sum of pairwise products; measures alignment", "Cross product 3D", "Outer product matrix", "Hadamard entrywise"],
    ["cross product", "3D vector orthogonal to two inputs", "Dot scalar", "Wedge in 2D only", "Kronecker product"],
    ["linear independence", "No vector is a linear combination of others", "Spanning set only", "Orthogonal set", "Orthonormal basis"],
    ["basis", "Linearly independent spanning set", "Generating set with deps", "Row echelon only", "Nullspace basis alone"],
    ["dimension", "Number of vectors in any basis", "Determinant value", "Rank deficiency", "Condition number"],
    ["span", "All linear combinations of a set of vectors", "Convex hull", "Affine hull only", "Orthogonal complement alone"],
    ["linear transformation", "Map preserving addition and scalar multiplication", "Affine translate", "Nonlinear activation", "Quadratic form"],
    ["matrix multiplication", "Composition of linear maps via row-column products", "Entrywise Hadamard", "Kronecker only", "Element sum"],
    ["transpose", "Matrix with rows and columns swapped", "Inverse matrix", "Adjugate cofactor", "Hermitian conjugate only"],
    ["inverse", "Matrix A^{-1} such that AA^{-1}=I", "Pseudoinverse rectangular", "Transpose only", "Diagonal scaling"],
    ["determinant", "Scalar volume scaling factor of a linear map", "Trace sum diagonal", "Rank count", "Norm length"],
    ["eigenvalue", "Scalar λ with Av=λv for nonzero v", "Singular value only", "Trace average", "Condition κ"],
    ["eigenvector", "Nonzero v satisfying Av=λv", "Singular vector only", "Nullspace arbitrary", "Row space vector"],
    ["diagonalization", "Writing A=PDP^{-1} with diagonal D", "SVD always", "QR factorization", "LU decomposition"],
    ["orthogonal", "Vectors with zero dot product", "Parallel vectors", "Linearly dependent", "Normalized only"],
    ["orthonormal", "Orthogonal set of unit vectors", "Orthogonal unnormalized", "Basis any", "Frame redundant"],
    ["norm", "Length measure satisfying vector norm axioms", "Inner product alone", "Metric distance only", "Seminorm degenerate"],
    ["projection", "Closest point in a subspace to a vector", "Reflection Householder", "Rotation Givens", "Shear map"],
    ["rank", "Dimension of column (or row) space", "Nullity only", "Determinant zero test alone", "Condition number"],
    ["nullspace", "Solutions to Ax=0", "Column space", "Row space", "Left nullspace twin alone"],
    ["SVD", "Factorization A=UΣV^T with orthogonal U,V", "Eigen EVD square only", "LU pivoting", "Cholesky SPD"],
    ["positive definite", "x^TAx>0 for all nonzero x", "Indefinite saddle", "Singular PSD boundary", "Orthogonal matrix"],
    ["condition number", "Sensitivity of solution to input perturbations", "Determinant magnitude", "Rank reveal", "Pivot growth"],
    ["Gaussian elimination", "Row operations to solve linear systems", "Jacobi iteration", "Conjugate gradient", "FFT multiply"],
    ["identity matrix", "Square matrix acting as multiplicative identity", "Zero matrix", "Exchange permutation", "Hilbert matrix"],
    ["affine transformation", "Linear map plus translation", "Pure linear origin-fixing", "Projective homogenize only", "Isometry rigid"],
    ["least squares", "Minimizing ||Ax-b|| for overdetermined systems", "Exact inverse solve", "Underdetermined null", "Eigenproblem"],
  ],
  arch: [
    ["CPU", "Central processor executing instructions", "GPU shader only", "DMA controller alone", "Southbridge chipset"],
    ["ALU", "Arithmetic logic unit performing integer ops", "FPU floating only", "Control unit decode", "Register file"],
    ["register", "Small fast storage inside the CPU", "Main DRAM", "Disk sector", "Cache line only"],
    ["clock cycle", "Basic timing quantum of synchronous logic", "Pipeline stall only", "Interrupt latency", "Bus transaction"],
    ["instruction set", "Machine operations a CPU can execute", "Microcode ROM only", "ABI calling convention", "Linker script"],
    ["RISC", "Reduced instruction set with simple ops", "CISC complex ops", "VLIW bundle only", "Stack machine"],
    ["CISC", "Complex instruction set with rich operations", "RISC load/store", "DSP MAC only", "GPU SIMT"],
    ["pipeline", "Overlapping instruction stages for throughput", "Single-cycle multi-cycle", "Out-of-order only", "Scoreboard"],
    ["hazard", "Condition preventing correct pipelined execution", "Cache miss only", "TLB shootdown", "Bus lock"],
    ["cache", "Fast memory holding recently used data", "Main memory DRAM", "Register renaming", "Write buffer only"],
    ["cache hit", "Requested data found in cache", "Compulsory miss", "Capacity miss", "Conflict miss"],
    ["virtual memory", "Abstraction mapping virtual to physical addresses", "Physical-only addressing", "Segment registers only", "DMA bounce"],
    ["TLB", "Cache of virtual-to-physical translations", "Page table walk only", "L1 data cache", "Branch predictor"],
    ["page fault", "Exception when translation or permission fails", "Segmentation fault userspace only", "Bus error", "NMI"],
    ["endianness", "Byte order for multi-byte values in memory", "Bit endian within byte only", "Alignment packing", "ABI padding"],
    ["bus", "Shared interconnect for components", "Point-to-point PCIe only", "NoC mesh only", "Crossbar alone"],
    ["interrupt", "Signal causing CPU to handle an event", "Polling loop only", "DMA completion alone", "Syscall trap only"],
    ["DMA", "Direct memory access by peripherals without CPU copy", "Programmed I/O", "Memory-mapped I/O only", "Interrupt coalesce"],
    ["flip-flop", "Edge-triggered bit storage element", "Combinational gate only", "Latch level-sensitive twin", "SRAM cell only"],
    ["combinational logic", "Outputs depend only on current inputs", "Sequential stateful", "Async FSM", "Clocked register"],
    ["sequential logic", "Outputs depend on inputs and state", "Pure combinational", "ROM lookup only", "PLA sum-of-products"],
    ["MUX", "Selects one of several inputs via select lines", "Decoder one-hot", "Encoder priority", "Adder carry"],
    ["decoder", "Converts binary input to one-hot outputs", "MUX select", "Priority encoder", "Demux route"],
    ["FSM", "Finite-state machine with states and transitions", "Turing machine infinite tape", "Petri net", "Dataflow graph"],
    ["boolean algebra", "Algebra of true/false with AND/OR/NOT", "Linear algebra", "Modular arithmetic", "Tropical semiring"],
    ["Karnaugh map", "Visual minimization of boolean functions", "Quine-McCluskey tabular", "Espresso heuristic", "BDD diagram"],
    ["two's complement", "Binary representation for signed integers", "Sign-magnitude", "Ones' complement", "Excess-n bias"],
    ["IEEE 754", "Standard for floating-point representation", "Fixed-point only", "BCD decimal", "Posit format only"],
    ["Harvard architecture", "Separate instruction and data memories", "Von Neumann unified", "Modified Harvard cache", "Stack machine"],
    ["von Neumann", "Shared memory for instructions and data", "Harvard split", "Dataflow token", "Systolic array"],
  ],
  os: [
    ["process", "Instance of a program in execution with its own address space", "Thread sharing AS", "Coroutine user", "Fiber lightweight"],
    ["thread", "Schedulable unit of execution within a process", "Process isolation", "Interrupt handler only", "Kernel module"],
    ["context switch", "Saving/restoring CPU state to change tasks", "Syscall transition only", "Page fault handle", "Signal delivery"],
    ["scheduling", "Selecting which ready task runs next", "Memory allocation", "I/O buffering", "IPC pipe"],
    ["mutex", "Lock ensuring mutual exclusion on a critical section", "Condition variable wait", "Semaphore counting only", "Spin barrier"],
    ["semaphore", "Counter for signaling and limiting concurrency", "Mutex binary only", "RWLock readers", "Futex wait"],
    ["deadlock", "Cycle of waits preventing progress", "Livelock spinning", "Starvation unfair", "Race benign"],
    ["race condition", "Outcome depends on uncontrolled timing", "Deterministic lockstep", "Deadlock cycle", "Priority inversion"],
    ["virtual memory OS", "Per-process address spaces backed by RAM/disk", "Physical contiguous only", "Segmentation alone", "Arena malloc"],
    ["page", "Fixed-size unit of virtual memory mapping", "Segment variable", "Cache line", "Disk block alone"],
    ["swap", "Moving pages between RAM and secondary storage", "Cache eviction only", "Compress zram only", "NUMA migrate"],
    ["file system", "Organization of files and directories on storage", "Block device raw", "Volume manager", "Object store API"],
    ["inode", "Metadata structure describing a file", "Directory entry name", "Superblock FS", "Journal txn"],
    ["system call", "Controlled entry from user to kernel services", "Library wrapper only", "Interrupt IRQ", "Hypercall VM"],
    ["kernel", "Privileged core managing hardware and abstractions", "Userland daemon", "Hypervisor L0", "Firmware BIOS"],
    ["user mode", "Restricted CPU privilege for applications", "Kernel ring 0", "Hypervisor root", "SMM mode"],
    ["interrupt handler", "Kernel routine responding to a hardware interrupt", "Syscall path", "Softirq bottom half only", "NMI watchdog"],
    ["IPC", "Mechanisms for processes to communicate", "Shared cache lines only", "DMA peer", "RPC remote only"],
    ["pipe", "Unidirectional byte stream between processes", "Socket network", "Shared memory map", "Message queue"],
    ["signal", "Async notification delivered to a process", "Exception CPU fault", "Eventfd Linux only", "Futex wake"],
    ["priority inversion", "Low-priority lock holder blocks higher priority", "Priority inheritance fix", "Deadlock cycle", "Convoy lock"],
    ["thrashing", "Excessive paging destroying useful progress", "Cache thrash only", "Scheduler convoy", "Lock contention"],
    ["copy-on-write", "Defer copying pages until a write occurs", "Eager deep copy", "Shared readonly only", "Relocate PIC"],
    ["daemon", "Background service process typically without TTY", "Interactive shell", "Kernel thread only", "Init script"],
    ["bootloader", "Program loading the OS kernel at startup", "Init system", "Firmware UEFI only", "kexec jump"],
    ["driver", "Software controlling a hardware device", "User library", "Syscall table", "cgroup controller"],
    ["cgroup", "Linux mechanism limiting resource usage of process groups", "namespace isolation only", "seccomp filter", "capabilities"],
    ["namespace", "Isolation of system resource views (pid, net, mnt)", "cgroup limits", "chroot alone", "container runtime"],
    ["preemption", "Forcibly interrupting a running task to schedule another", "Cooperative yield only", "Interrupt disable", "Soft affinity"],
    ["critical section", "Code accessing shared state needing synchronization", "Lock-free algorithm", "Read-only path", "RCU grace"],
  ],
  networks: [
    ["OSI model", "Seven-layer conceptual network stack", "TCP/IP four-layer", "SOAP envelope", "RPC stub"],
    ["TCP/IP model", "Internet layering: link, internet, transport, application", "OSI seven exact", "SS7 telephony", "InfiniBand verbs"],
    ["IP", "Internet Protocol for addressing and routing packets", "TCP reliability", "UDP datagrams", "ICMP control only"],
    ["TCP", "Reliable ordered byte-stream transport", "UDP unreliable", "QUIC always", "SCTP multi-homing"],
    ["UDP", "Unreliable connectionless datagram transport", "TCP handshake", "TLS record", "HTTP/2 streams"],
    ["HTTP", "Application protocol for web request/response", "FTP file transfer", "SMTP mail", "DNS query"],
    ["DNS", "Resolves domain names to IP addresses", "DHCP address lease", "ARP MAC resolve", "NTP time"],
    ["DHCP", "Dynamically assigns IP configuration to hosts", "DNS lookup", "NAT translation", "BGP route"],
    ["NAT", "Rewrites addresses to share public IPs", "Firewall ACL only", "VPN tunnel", "Proxy forward"],
    ["routing", "Selecting paths for packets across networks", "Switching L2 only", "Bridging flood", "Load balance L7"],
    ["switching", "Forwarding frames within a Layer-2 domain", "IP routing", "NAT rewrite", "MPLS label"],
    ["MAC address", "Link-layer hardware address", "IPv4 host", "Port number", "ASN BGP"],
    ["subnet mask", "Bits distinguishing network and host portions", "Default gateway", "DNS suffix", "MTU size"],
    ["CIDR", "Prefix-length notation for IP networks", "Classful A/B/C only", "NAT pool", "VLAN tag"],
    ["port number", "Transport demux identifier for applications", "IP protocol number", "Ethertype", "VLAN ID"],
    ["three-way handshake", "TCP SYN/SYN-ACK/ACK connection setup", "UDP connect", "TLS 1-RTT", "QUIC 0-RTT"],
    ["congestion control", "Adjusting send rate to avoid network overload", "Flow control window only", "QoS marking", "Traffic shape"],
    ["flow control", "Preventing sender from overwhelming receiver", "Congestion AIMD", "Priority queue", "ECN bit"],
    ["packet", "Network-layer unit of data", "Frame L2", "Segment TCP", "Message app"],
    ["latency", "Time delay for data to traverse a path", "Bandwidth capacity", "Jitter variance", "Loss rate"],
    ["bandwidth", "Data capacity of a link over time", "Latency delay", "Goodput app", "RTT measure"],
    ["RTT", "Round-trip time for a packet and its ack", "One-way delay", "Jitter buffer", "Timeout RTO"],
    ["TLS", "Cryptographic protocol securing application streams", "IPsec network", "SSH shell", "WPA wireless"],
    ["firewall", "Policy filter for permitted traffic", "IDS detect only", "WAF app only", "Proxy cache"],
    ["CDN", "Distributed caches delivering content near users", "Origin server only", "Anycast DNS alone", "Load balancer L4"],
    ["BGP", "Inter-domain routing protocol of the Internet", "OSPF intra-domain", "RIP distance", "IS-IS link"],
    ["ARP", "Maps IPv4 addresses to MAC on a LAN", "NDP IPv6", "DNS A record", "DHCP offer"],
    ["MTU", "Maximum transmission unit size of a link", "MSS TCP", "Window scale", "Jumbo frame only"],
    ["socket", "Endpoint abstraction for network communication", "File inode", "Pipe FIFO", "Shared memory"],
    ["REST", "HTTP-centric architectural style for APIs", "SOAP RPC XML", "gRPC streams only", "GraphQL query only"],
  ],
  cybersecurity: [
    ["CIA triad", "Confidentiality, integrity, and availability goals", "AAA accounting only", "STRIDE threats", "OWASP top"],
    ["authentication", "Verifying claimed identity", "Authorization rights", "Accounting audit", "Encryption secrecy"],
    ["authorization", "Granting permissions to authenticated principals", "Authentication identity", "Auditing logs", "Non-repudiation"],
    ["encryption", "Transforming plaintext to ciphertext with a key", "Hashing one-way", "Encoding Base64", "Obfuscation trivial"],
    ["hashing", "One-way digest for integrity and commitments", "Encryption reversible", "MAC keyed", "Signature asymmetric"],
    ["malware", "Malicious software harming systems or data", "Benign bug", "Phishing social only", "Misconfig drift"],
    ["phishing", "Social engineering via deceptive messages", "SQL injection", "Buffer overflow", "XSS stored"],
    ["XSS", "Injecting scripts into web pages viewed by others", "CSRF request forge", "SQLi query", "SSRF server"],
    ["SQL injection", "Inserting attacker SQL via unsanitized input", "XSS script", "Command injection twin", "LDAP inject"],
    ["CSRF", "Forcing authenticated users to submit unwanted requests", "XSS steal cookie", "Clickjacking UI", "CORS misconfig"],
    ["privilege escalation", "Gaining higher rights than intended", "Lateral movement", "Persistence implant", "Exfil channel"],
    ["firewall cyber", "Network filter enforcing allow/deny policies", "IDS signature", "EDR endpoint", "SIEM correlate"],
    ["IDS", "Intrusion detection monitoring for attacks", "IPS blocking twin", "Firewall stateful", "Honeypot decoy"],
    ["IPS", "Intrusion prevention that can block traffic", "IDS alert only", "WAF rules", "NAC admit"],
    ["VPN", "Encrypted tunnel for remote network access", "TLS website only", "SSH port forward alone", "Tor onion"],
    ["zero trust", "Never trust, always verify access model", "Castle-and-moat perimeter", "VPN-only trust", "Air gap alone"],
    ["MFA", "Multi-factor authentication combining factors", "Password only", "SSO federation alone", "Certificate pin"],
    ["vulnerability", "Weakness that can be exploited", "Threat actor", "Exploit payload", "Risk residual"],
    ["exploit", "Technique/code taking advantage of a vulnerability", "Patch fix", "CVE catalog entry", "PoC writeup only"],
    ["CVE", "Common Vulnerabilities and Exposures identifier", "CWE weakness class", "CVSS score", "NVD feed"],
    ["penetration test", "Authorized simulated attack to find weaknesses", "Vulnerability scan only", "Red team full", "Bug bounty"],
    ["social engineering", "Manipulating people to divulge access or info", "Cryptanalysis math", "Fuzzing inputs", "Side channel"],
    ["ransomware", "Malware encrypting data for extortion", "Spyware observe", "Worm self-replicate", "Rootkit hide"],
    ["least privilege", "Granting only necessary permissions", "Need-to-know data", "Defense in depth", "Separation of duties"],
    ["defense in depth", "Layered overlapping controls", "Single strong control", "Security through obscurity", "Perimeter only"],
    ["certificate", "Signed binding of identity to a public key", "Raw public key", "Password hash", "OTP seed"],
    ["PKI", "Infrastructure for issuing and validating certificates", "Symmetric KMS only", "Web of trust PGP", "SSH known_hosts"],
    ["secure SDLC", "Integrating security throughout development", "Pen-test at end only", "Ops firewall only", "Compliance checkbox"],
    ["logging", "Recording security-relevant events for analysis", "Metrics gauges", "Tracing spans", "Alerting pages"],
    ["incident response", "Process to detect, contain, and recover from breaches", "Threat modeling design", "Tabletop exercise only", "Forensics disk only"],
  ],
  crypto: [
    ["symmetric encryption", "Same key used to encrypt and decrypt", "Public-key pair", "One-way hash", "Digital signature"],
    ["asymmetric encryption", "Public encrypt / private decrypt key pair", "Shared secret only", "MAC integrity", "Stream cipher"],
    ["AES", "Widely used symmetric block cipher standard", "RSA public-key", "SHA-256 hash", "ChaCha20 stream twin"],
    ["RSA", "Public-key system based on factoring hardness", "ECC curves", "Diffie-Hellman KE", "AES-GCM"],
    ["ECC", "Public-key crypto using elliptic curve discrete log", "RSA moduli", "DSA finite field", "Lattice Kyber"],
    ["hash function", "Deterministic one-way fixed-length digest", "PRP cipher", "PRF keyed", "KDF stretch"],
    ["SHA-256", "256-bit cryptographic hash in SHA-2 family", "MD5 broken", "SHA-1 weak", "Blake3 fast"],
    ["MAC", "Keyed integrity tag authenticating a message", "Unkeyed hash", "Digital signature asymmetric", "CRC checksum"],
    ["HMAC", "MAC construction using a hash function and key", "CMAC block", "Poly1305 AEAD", "GCM tag"],
    ["digital signature", "Asymmetric proof of origin and integrity", "MAC shared key", "Encryption secrecy", "Commitment hide"],
    ["Diffie-Hellman", "Key agreement over public channel", "RSA encrypt message", "AES session", "PAKE password"],
    ["nonce", "Number used once to prevent replay", "Salt password", "IV cipher mode", "Counter block"],
    ["IV", "Initialization vector for cipher modes", "Key material", "Salt KDF", "Nonce AEAD"],
    ["salt", "Random value mixed into password hashing", "Pepper secret", "IV CBC", "Nonce GCM"],
    ["KDF", "Derives keys from passwords or key material", "RNG entropy", "PRNG stream", "Hash compress"],
    ["PBKDF2", "Password-based KDF with iterated HMAC", "bcrypt adaptive", "scrypt memory", "Argon2 winner"],
    ["perfect forward secrecy", "Past sessions safe if long-term key leaks", "Static RSA key exchange", "Session ticket immortal", "PSK only"],
    ["certificate crypto", "Signed statement binding identity to public key", "Self-signed trust anchor alone", "Raw key pin", "TOFU SSH"],
    ["CA", "Certificate authority issuing trusted certs", "RA registration", "OCSP status", "CRL list"],
    ["TLS handshake", "Negotiates keys and authenticates endpoints", "TCP handshake", "IPsec IKE twin", "SSH kex"],
    ["side-channel attack", "Exploits timing/power/cache leakage", "Cryptanalysis math only", "Brute force keyspace", "Social engineer"],
    ["chosen plaintext", "Attacker can encrypt chosen messages", "Ciphertext only", "Known plaintext", "Chosen ciphertext"],
    ["IND-CPA", "Indistinguishability under chosen-plaintext attack", "INT-CTXT integrity", "EUF-CMA signatures", "CCA2 decryption"],
    ["stream cipher", "Encrypts by XORing a keystream", "Block ECB", "Feistel network", "SPN AES"],
    ["block cipher", "Encrypts fixed-size blocks under a key", "Stream OTP", "Hash sponge", "Public trapdoor"],
    ["mode of operation", "How a block cipher secures arbitrary-length data", "Key schedule", "S-box design", "Feistel round"],
    ["GCM", "Authenticated encryption mode with GHASH tag", "CBC+HMAC compose", "CTR unauth", "ECB insecure"],
    ["zero-knowledge proof", "Prove statement without revealing witness", "Commitment hide-open", "Blind signature", "MPC share"],
    ["post-quantum", "Crypto intended to resist quantum attacks", "Classical RSA forever", "Symmetric only double", "Hash-based only"],
    ["entropy", "Unpredictability of a secret or RNG source", "Key length bits alone", "Confusion diffusion", "Avalanche hash"],
  ],
  databases: [
    ["relation", "Table of tuples under a schema", "Document collection", "Graph nodes", "Key-value pair"],
    ["primary key", "Unique identifier for rows in a table", "Foreign key ref", "Secondary index", "Surrogate UUID alone"],
    ["foreign key", "Column referencing another table's key", "Primary uniqueness", "Check constraint", "Unique index"],
    ["SQL", "Declarative language for relational data", "Procedural PL only", "Graph QL only", "Mongo MQL"],
    ["SELECT", "Query clause retrieving rows/columns", "INSERT write", "UPDATE modify", "DELETE remove"],
    ["JOIN", "Combines rows from tables on a condition", "UNION set", "GROUP BY agg", "WINDOW frame"],
    ["INNER JOIN", "Returns matching rows from both sides", "LEFT OUTER keep left", "CROSS product", "FULL OUTER"],
    ["LEFT JOIN", "Keeps all left rows; nulls when no match", "INNER matches only", "RIGHT twin", "SEMI exists"],
    ["WHERE", "Filters rows before grouping", "HAVING after group", "ON join cond", "QUALIFY window"],
    ["GROUP BY", "Aggregates rows sharing key values", "ORDER BY sort", "DISTINCT dedupe", "PARTITION BY"],
    ["HAVING", "Filters groups after aggregation", "WHERE pre-agg", "LIMIT count", "OFFSET skip"],
    ["index", "Auxiliary structure speeding lookups", "Full table scan", "Materialized view", "Sequence object"],
    ["B-tree index", "Balanced tree index for range and equality", "Hash equality only", "Bitmap flags", "GIN inverted"],
    ["transaction", "Atomic unit of reads/writes", "Autocommit statement", "Savepoint nest", "2PC prepare"],
    ["ACID", "Atomicity, consistency, isolation, durability", "BASE eventual", "CAP theorem", "PACELC latency"],
    ["isolation level", "Controls visibility of concurrent transactions", "Lock timeout", "Deadlock victim", "MVCC snapshot"],
    ["normalization", "Reducing redundancy via schema design", "Denormalize speed", "Star schema BI", "Wide column"],
    ["1NF", "Atomic attribute values; no repeating groups", "2NF partial deps", "3NF transitive", "BCNF determinants"],
    ["2NF", "1NF plus no partial dependency on composite key", "3NF transitive", "DKNF domain", "4NF MVD"],
    ["3NF", "No transitive dependency of non-keys on key", "BCNF stricter", "EKNF", "5NF join"],
    ["view", "Stored query presented as a virtual table", "Materialized cached", "Temp table", "CTE with"],
    ["stored procedure", "Server-side procedural routine", "Trigger event", "UDF scalar", "Prepared statement"],
    ["trigger", "Automatic action fired by table events", "Check constraint", "Rule rewrite", "Event notify"],
    ["ORM", "Maps objects to relational tables", "Raw SQL only", "Query builder", "Data mapper twin"],
    ["NoSQL", "Non-relational stores (doc/kv/col/graph)", "Only SQL engines", "NewSQL hybrid", "CSV files"],
    ["document store", "Database of JSON-like documents", "Wide-column", "Graph edges", "Time-series"],
    ["CAP theorem", "Tradeoffs among consistency, availability, partition tolerance", "ACID local", "BASE soft", "PACELC"],
    ["replication", "Copying data across nodes for HA/scale", "Sharding partition", "Backup dump", "Failover VIP"],
    ["sharding", "Partitioning data across multiple servers", "Replica copy", "Vertical scale", "Federation"],
    ["EXPLAIN", "Shows the query planner's chosen plan", "ANALYZE stats", "VACUUM clean", "REINDEX rebuild"],
  ],
  parallel: [
    ["parallelism", "Doing multiple operations simultaneously", "Concurrency interleaving", "Async callbacks", "Pipelining stages"],
    ["concurrency", "Structuring overlapping task progress", "Parallel multicore only", "SIMD vector", "GPU SIMT"],
    ["speedup", "Ratio of sequential time to parallel time", "Efficiency utilization", "Amdahl serial", "Gustafson scale"],
    ["Amdahl's law", "Limits speedup given a serial fraction", "Gustafson scaled", "Little's law", "Universal scalability"],
    ["shared memory", "Threads communicate via common address space", "Message passing", "DSM distributed", "RDMA remote"],
    ["message passing", "Processes communicate by sending messages", "Shared heap", "Lock-free queue only", "RPC stub alone"],
    ["MPI", "Standard API for distributed message passing", "OpenMP shared", "CUDA kernels", "Spark RDD"],
    ["OpenMP", "Pragma-based shared-memory parallelism", "MPI ranks", "TBB tasks", "Cilk spawn"],
    ["race condition parallel", "Bug from unsynchronized concurrent access", "Deterministic reduce", "Barrier sync", "Atomic RMW"],
    ["barrier", "Synchronization where all must arrive before proceed", "Mutex lock", "Condition wait", "Latch count"],
    ["lock-free", "Algorithm guaranteeing system-wide progress without locks", "Blocking mutex", "Wait-free stronger", "Obstruction-free"],
    ["atomic operation", "Indivisible read-modify-write at hardware/API", "Volatile load", "Mutex critical", "Memory fence only"],
    ["false sharing", "Performance hit when cores bounce same cache line", "True data race", "NUMA remote", "TLB shootdown"],
    ["NUMA", "Memory access cost depends on locality to CPU", "UMA uniform", "COMA cache-only", "GPU HBM"],
    ["load balancing", "Distributing work to avoid idle workers", "Work stealing", "Static partition", "Central queue"],
    ["work stealing", "Idle workers take tasks from busy workers' queues", "Central dispatcher", "Static chunks", "Actor mailbox"],
    ["MapReduce", "Parallel map then shuffle-reduce paradigm", "MPI collective only", "BSP superstep", "Stream process"],
    ["distributed system", "Multiple networked computers coordinating", "SMP shared", "Single host threads", "Embedded RTOS"],
    ["consensus", "Agreeing on a value despite faults", "Gossip eventual", "Leader election alone", "Quorum read"],
    ["Paxos", "Classic consensus protocol family", "Raft simpler", "2PC commit", "Zab ZK"],
    ["Raft", "Consensus protocol with leader election and log", "Paxos multi", "PBFT Byzantine", "Viewstamped"],
    ["CAP parallel", "Consistency/availability/partition tradeoffs", "ACID single node", "BASE soft state", "FLP impossibility"],
    ["eventual consistency", "Replicas converge if updates stop", "Strong linearizability", "Causal order", "Sequential consistency"],
    ["RPC", "Calling a procedure on a remote machine", "Local function", "Message queue async", "gRPC HTTP/2"],
    ["actor model", "Isolated actors communicate via messages", "Shared-memory threads", "CSP channels twin", "Dataflow tokens"],
    ["SIMD", "Single instruction operates on multiple data lanes", "MIMD multicore", "MISD rare", "SISD scalar"],
    ["GPU computing", "Massively parallel throughput on accelerators", "CPU latency cores", "FPGA fabric", "TPU systolic"],
    ["deadlock parallel", "Circular wait among concurrent tasks", "Livelock retry", "Starvation unfair", "Priority invert"],
    ["scalability", "Ability to handle growth by adding resources", "Latency absolute", "Throughput peak only", "Efficiency ratio"],
    ["straggler", "Slow task delaying overall completion", "Speculative retry fix", "Skew key", "Hot partition"],
  ],
  compilers: [
    ["lexer", "Tokenizer converting source text to tokens", "Parser AST", "Semantic analyzer", "Codegen emitter"],
    ["parser", "Builds syntactic structure from tokens", "Lexer scan", "Type checker", "Optimizer pass"],
    ["AST", "Abstract syntax tree representing program structure", "CST concrete", "CFG control-flow", "SSA form"],
    ["CFG grammar", "Context-free grammar describing syntax", "Regular lexer", "Attribute grammar", "PEG parser"],
    ["LL parser", "Top-down leftmost derivation parser", "LR bottom-up", "LALR table", "GLR ambiguous"],
    ["LR parser", "Bottom-up shift-reduce parser", "Recursive descent LL", "Pratt precedence", "Earley general"],
    ["semantic analysis", "Checks types and meaning beyond syntax", "Lexing tokens", "Parsing CFG", "Register alloc"],
    ["type checking", "Ensuring expressions obey type rules", "Name resolution", "Control-flow", "Dataflow liveness"],
    ["IR", "Intermediate representation between front and back ends", "Source text", "Machine code", "Object file"],
    ["SSA", "Static single assignment form of IR", "Three-address naive", "CPS continuation", "ANF admin"],
    ["optimization", "Transforms improving performance/size preserving semantics", "Pretty print", "Desugar only", "Link edit"],
    ["constant folding", "Evaluating constant expressions at compile time", "CSE eliminate", "DCE dead", "Inlining"],
    ["dead code elimination", "Removing unreachable or unused computations", "Loop unrolling", "Strength reduce", "Peephole"],
    ["inlining", "Replacing a call with the callee body", "Tail call opt", "Outlining", "Specialization"],
    ["register allocation", "Assigning temporaries to machine registers", "Instruction select", "Scheduling issue", "Spill store"],
    ["instruction selection", "Mapping IR ops to target instructions", "Regalloc coloring", "Peephole local", "ABI lower"],
    ["linking", "Combining object files and resolving symbols", "Assembling mnemonics", "Loading runtime", "Relocating"],
    ["symbol table", "Maps identifiers to attributes/bindings", "Relocation table", "String pool", "VTable layout"],
    ["scope", "Region where a name binding is visible", "Lifetime storage", "Linkage extern", "Namespace C++"],
    ["binding", "Association of a name with a language entity", "Assignment store", "Capture closure", "Import module"],
    ["closure", "Function plus its captured environment", "Function pointer bare", "Object method", "Coroutine frame"],
    ["runtime system", "Support services for executed programs", "Compiler frontend", "OS kernel", "Assembler"],
    ["JIT", "Compile to native code at runtime", "AOT ahead-of-time", "Interpreter loop", "Transpile source"],
    ["interpreter", "Executes source/IR by direct evaluation", "Native binary", "Bytecode VM twin", "Macro expander"],
    ["bytecode compilers", "Portable instruction set for a VM", "Native ISA", "SSA IR only", "WASM module twin"],
    ["type inference", "Deducing types without full annotations", "Dynamic typing", "Gradual checks", "Dependent proof"],
    ["overloading", "Multiple entities sharing a name distinguished by types", "Overriding dynamic", "Shadowing nest", "Aliasing typedef"],
    ["name mangling", "Encoding symbol names with type info for linkers", "Demangling tools", "Decorated Windows", "Export ordinal"],
    ["frontend", "Lex/parse/semantic phases of a compiler", "Backend codegen", "Middle-end opt", "Driver CLI"],
    ["backend", "Code generation and machine-specific passes", "Frontend parse", "Typecheck", "Macro hygiene"],
  ],
};
